# -*- coding: utf-8 -*-
"""Day-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Shx3p44qhfwCswTiFy2KknedHbsFJsTg
"""

!pip install sentence-transformers chromadb groq pandas -q

import pandas as pd
import chromadb #vector database
from sentence_transformers import SentenceTransformer #convert string to integer
from groq import Groq
import os

GROQ_API_KEY="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"
os.environ["GROQ_API_KEY"]=GROQ_API_KEY
groq_client=Groq(api_key=GROQ_API_KEY)

print("GRoq Api client initialized")

df=pd.read_csv('college_notes.csv')
print(df.shape)

print(df.columns.tolist())
print(df.head(3))

print(df['subject'].value_counts())
print(df[['note_id','subject','topic']].head(3).to_string(index=False))

df['content_length']=df['content'].apply(len)
print(df[['topic','content_length']].to_string(index=False))

documents=df['content'].tolist()
ids=[f"note_{row['note_id']}" for row in df.to_dict('records')]
metadatas=[
    {"subject":row['subject'],"topic":row['topic']}
    for row in df.to_dict('records')
]


print(f"Total chunk prepared:{len(documents)}")
print(f"First document ID : {ids[0]}")
print(f"First metadata :{metadatas[0]}")
print(f"First 100 chars of doc:{documents[0][:100]}")

embedding_model=SentenceTransformer('all-MiniLM-L6-v2')

test_embedding=embedding_model.encode("Tis is a test sentence")

print(f"Test embedding shape:{test_embedding.shape}")
print(f"First 5 values of test embedding:{test_embedding[:5]}")

chroma_client=chromadb.Client()
collection=chroma_client.get_or_create_collection(name="college_notes_rag")
print("chromadb client created.")
print(f"collection name:college_notes_rag")
print(f"Documents in collection so far:{collection.count()}")

embeddings= embedding_model.encode(documents,show_progress_bar=True)

print(f'\nEmbedding matrix shape:{embeddings.shape}')

embeddings_list=embeddings.tolist()

collection.add(
    documents=documents,
    embeddings=embeddings_list,
    ids=ids,
    metadatas=metadatas
)

print(f"Total documents in collection:{collection.count()}")

def retrieve_relevant_chunks(question, top_k = 3):
  """
  Given a user question, retrieve the most relevant document chunks from chromaDB.

  Parameters:
  question(str) : The user's question as a text string
  top_k(int) : Howmnay top results to return (default : 3)

  Returns:
  A dictionary containing retrieved documents, distances and metadata
  """

  question_embedding = embedding_model.encode(question).tolist()
  results = collection.query(
      query_embeddings = [question_embedding],
      n_results = top_k
  )
  return results
print("Retrieval function defined successfully!")

test_question="What is ETL and how does it work in data engineering?"
print(f"Test_question:{test_question}")
results=retrieve_relevant_chunks(test_question,top_k=3)


for i,(doc,dist,meta) in enumerate(zip(
    results['documents'][0],
    results['distances'][0],
    results['metadatas'][0]
)):
    print(f"\nresult {i+1}")
    print(f"Subject:{meta['subject']}")
    print(f"Topic:{meta['topic']}")
    print(f"Distance:{dist:.4f}")
    print(f"content:{doc[:120]}...")

def build_context_from_results(results):
  """
  Format chromaDB retrieval results into the readable context string.
  parmeters:
   results: the ouptput from collection.query()-a dictionary
  returns:
   context_str(str): A formatted string of all retrieved document chunks
  """
  context_parts=[]
  for i,(doc,meta) in enumerate(zip(
      results['documents'][0],
      results['metadatas'][0]
  )):
     chunk_text=f"[source{i+1}:{meta['subject']}-{meta['topic']}]\n{doc}"

def generate_rag_answer(question,context):
  """
  send the retrieved context and question to the groq LLM for tanswer generation

  Parameters:
   question(str):the user's question
   context (str):the retrieved context chunks(formatted string)

  return:
   answer(str):the LLM's generated answer

  """

  system_prompt ="""You are a helpful academic assistant for engineering students.
  you will be given context retrieved from a college knowledge base and a student's question


  RULES:
  1. Answer only using the information provided in the context below
  2. if the answer is not found in the context, say exactly:
  "I don't have enough information in my knowledge base to answer this question"
  3.Do not use your general training knowledge
  4. keep answers clear, accurate, and beginner-friendly
  5. Mention which source the information came from when possible
  """
  user_prompt=f"""Context from knowledgeBase:
  {context}
  ---
  Student's question :{question}
  Please answer the question based only on the context provided above"""

  response=groq_client.chat.completions.create(
      model="llama-3.1-8b-instant",
      messages=[
          {"role":"system","content":system_prompt},
          {"role":"user","content":user_prompt}
      ],
      temperature=0.1,
      max_tokens=500
  )
  answer=response.choices[0].message.content
  return answer
print("RAG generation function defined")

def ask_college_assistant(question, top_k=3,verbose=True):
  """complete RAG