# -*- coding: utf-8 -*-
"""Day10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1En3HiSDBB-Lk0-RDZGJP50xNft3d1G9P
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

df=pd.read_csv('student_performance.csv')

print(df.head())

conn=sqlite3.connect('college.db')
cursor = conn.cursor()

df.to_sql("students", conn, if_exists="replace", index=False)

result = pd.read_sql("SELECT * FROM students LIMIT 5", conn)

print(result)

def run_query(sql,description="students"):
  if description:
    print(f"{description}")

  result=pd.read_sql_query(sql,conn)
  print(result.to_string(index=False))
  return result

query1="""
  SELECT student_id,name,department,math_score,attendance_percentage
  FROM students
  LIMIT 10
"""
result1=run_query(query1,"Query 1:First 10 Students (SELECT + LIMIT)")

chart1_sql="""
SELECT student_id,name,department,math_score,attendance_percentage
  FROM students
  GROUP BY department
ORDER BY attendance_percentage DESC
  LIMIT 10
"""

chart1_data=pd.read_sql_query(chart1_sql,conn)

fig,ax=plt.subplots(figsize=(10,6))

bar_colors=['red','pink','blue','purple']

bars = ax.bar(
    chart1_data['department'],
    chart1_data['attendance_percentage'],
    color= bar_colors,
    edgecolor='white',
    linewidth=0.8
)

for bar in bars:
  h=bar.get_height()
  ax.text(
      bar.get_x() + bar.get_width()/2,
      h+0.8,
      f'{h:.1f}',
      ha='center',va='bottom',
      fontsize=12,fontweight='bold',
      color='green'
  )
ax.set_title('Avg attendance score',fontsize=16,fontweight='bold',pad=15)
ax.set_xlabel('Department',fontsize=13)
ax.set_ylabel('Avg attendance score',fontsize=13)
ax.set_ylim(0,105)
ax.tick_params(axis='x',labelsize=11)
ax.grid(axis='y',alpha=0.3,linestyle='--')

plt.tight_layout()
plt.show()

raw_df=pd.read_csv('messy_sales_data.csv')
print(f'Raw data loaded:{raw_df.shape[0]} rows,{raw_df.shape[1]} columns')
print(f'Columns:{[raw_df.columns.tolist()]}')
raw_df.head()

print("Quantity:")
print(raw_df['quantity'].isnull().sum())

df=raw_df.copy()
print(f'Working copy created:{df.shape}')

print(raw_df.isnull().sum())

print(f'\nDUPLICATE ROWS:{raw_df.duplicated().sum()}')
print(raw_df.dtypes)
 # unique value intext columns
print('\n Unique categories',raw_df['category'].unique())
print(' Sample customer name:',raw_df['customer_name'].dropna().unique()[:8])
print(' Sample order_date values:',raw_df['order_date'].unique()[:6])

print('before fixing nulls:',df.isnull().sum().sum(),'total missing values')
df['customer_name'].fillna('Unknown customer',inplace=True)
median_qty=df['quantity'].median()
df['quantity'].fillna('median_qty',inplace=True)
print(f'Filled missing quantity with median:{median_qty}')
df['category'].fillna('uncategorized',inplace=True)
print('after fixing nulls:',df.isnull().sum().sum(),'total missing values')

print(f'Before deduplicated:{len(df)} rows')
print(f'Duplicate rows:{df.duplicated().sum()}')
print('\nDuplicate rows:')
print(df[df.duplicated(keep=False)][['order_id','customer_name','product']])
df.drop_duplicates(inplace=True)
print(f'\nAfter deduplication:{len(df)} rows')
print(f'Rows removed:{len(raw_df)-len(df)}')

print('before fixing nulls:',df.isnull().sum().sum(),'total missing values')
df['product'].fillna('Unknown product',inplace=True)
print('after fixing nulls:',df.isnull().sum().sum(),'total missing values')

import requests

# Your OpenWeatherMap API Key
API_KEY = "701c6832a4e89a42f7a52c86ac84c159"

# City Name
city = "Chennai"

# API URL
url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

# Send Request
response = requests.get(url)

# Convert JSON Response
data = response.json()

# Check if request was successful
if response.status_code == 200:
    temperature = data["main"]["temp"]
    humidity = data["main"]["humidity"]
    description = data["weather"][0]["description"]

    print(f"City: {city}")
    print(f"Temperature: {temperature}°C")
    print(f"Humidity: {humidity}%")
    print(f"Weather: {description}")
else:
    print("Error:", data.get("message"))

!pip install pyspark --quiet
print('Pyspark installation complete!')

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year,month,to_date,col,round as spark_round
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')


#SparkSession
spark=SparkSession.builder \
.appName('Day4_BigData_Sales')\
.config('spark.sql.adaptive.enabled','true')\
.getOrCreate()


print(f'Spark Session : {spark.version}')

df_bronze = spark.read \
.option('header','true') \
.option('inferSchema','true') \
.csv('large_sales_data.csv')

print('BRONZE LAYER-Raw Data')
print(f'Rows : {df_bronze.count()}')
print(f'Columns : {len(df_bronze.columns)}')
print(f'Names : {df_bronze.columns}')

print()
df_bronze.printSchema()

print('First 5 rows:')
df_bronze.show(5,truncate=False)

print('\nBasic statistics for numeric columns:')
df_bronze.select('quantity','unit_price','revenue').describe().show()

print('Last 5 rows:')
df_bronze.tail(5)

df_bronze.write \
.mode('overwrite') \
.parquet('sales_bronze.parquet')

print('Bronze parquet saved:sales_bronze.parquet')

import os

def get_dir_size(path):
  """get total size of a file or directory in KB."""
  if os.path.isfile(path):
    return os.path.getsize(path) / 1024
  total=0
  for dirpath,dirnames,filenames in os.walk(path):
    for f in filenames:
      total+=os.path.getsize(os.path.join(dirpath,f))
  return total/1024

csv_size=get_dir_size('large_sales_data.csv')
parquet_size=get_dir_size('sales_bronze.parquet')
reduction=(1 - parquet_size/csv_size)*100

print(f'Parquet size:{parquet_size:.1f} KB')
print(f'CSV size:{csv_size:.1f} KB')
print(f'Reduction in size:{reduction:.1f}% smaller')

df_silver=df_bronze \
 .dropDuplicates() \
 .dropna(subset=['order_id','product','revenue'])

df_silver=df_silver.withColumn(
     'order_date',
     to_date(col('order_date'),'dd-MM-yyyy')
)

df_silver=df_silver \
  .withColumn('order_year',year(col('order_date'))) \
  .withColumn('order_month',month(col('order_date')))

df_silver=df_silver.withColumn(
      'revenue category',
      F.when(col('revenue')>30000,'high')
      .when(col('revenue')>10000,'medium')
      .otherwise('low')
  )
print(f'Rows : {df_silver.count()}')
print('new columns added:order_year,order_month,revenue_category')
df_silver.select('product','revenue','order_year','order_month','revenue category').show(8)

df_silver.write \
.mode('overwrite') \
.parquet('sales_silver.parquet')

print('Silver parquet saved:sales_silver.parquet')
print(f'Silver size:{get_dir_size("sales_silver.parquet"):.1f} KB')

print('Bronze parquet saved:sales_bronze.parquet')
print(f'Bronze size:{get_dir_size("sales_bronze.parquet"):.1f} KB')


df_verify=spark.read.parquet('sales_silver.parquet')
print(f'Read-back rows: {df_verify.count()}(should match silver count)')
df_verify.printSchema()

from sklearn.model_selection import train_test_split  #scikit learn
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df= pd.read_csv('student_performance.csv')
print(f'Dataset loaded:{df.shape[0]} students,{df.shape[1]} columns')
print(f'columns: {df.columns.tolist()}')
print(f'\n missing values:{df.isnull().sum().sum()}')
df.head()
print(df['programming_score'].describe())

df_ml=df.copy()
le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f'Gender encoding:{dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')
le_dept=LabelEncoder()
df_ml['department_encoded']=le_dept.fit_transform(df_ml['department'])
print(f'department encoding:{dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')

df_ml[['gender','gender_encoded','department','department_encoded']].head(5)

feature_cols=[
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoded',
    'department_encoded'
]
x=df_ml[feature_cols]
y=df_ml['programming_score']

print(f'feature matrix X shape:{x.shape} students x features')
print(f'Target vector y shape:{y.shape} (one score per student)')
print(f'\nFeature columns:{feature_cols}')
print(f'Target column:programming_score')

print(f'\nTarget range:{y.min()} to {y.max()} (mean:{y.mean():.1f})')

x_train,x_test,y_train,y_test=train_test_split(
    x,y,
    test_size=0.2,
    random_state=42
)

print(f'Total students:{len(x)}')
print(f'Training students:{len(x_train)}({len(x_train)/len(x)*100:.0f}%)')
print(f'Testing Students:{len(x_test)}({len(x_test)/len(x)*100:.0f}%)')
print(f'\nTraining target range:{y_train.min()} - {y_train.max()}')
print(f'Testing target range : {y_test.min()}-{y_test.max()}')

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

print('Features scaled successfully!')
print(f'Training feature mean: {x_train_scaled.mean():.3f}')
print(f'Training feature standard deviation: {x_train_scaled.std():.3f}')

lr_model=LinearRegression()
lr_model.fit(x_train_scaled,y_train)
lr_pred=lr_model.predict(x_test_scaled)

lr_mae=mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)

print(f'Mae :{lr_mae:.2f}(predictions are off by {lr_mae:.1f} points on average)')
print()
print(f'rmse:{lr_rmse:.2f} (error with penalty for large mistakes)')
print()
print(f'R2 : {lr_r2:.4f} ({lr_r2*100:.1f}% of programming score variation explained)')
print()
print('Learned coefficients (importance of each feature)')
for feat,coef in zip(feature_cols,lr_model.coef_):
  print(f'{feat:<28}:{coef:+.3f}')
print(f'{"bias(intercept)":<28}:{lr_model.intercept_:+.3f}')

!pip install chromadb sentence-transformers -q

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb

print('all libraries imported')
print(f"ChromaDB version:{chromadb.__version__}")

documents=[


]

query_keyboard="vehicle"

print(f"beyond search for:'{query_keyboard}")

for i, doc in enumerate(documents):
  if query_keyboard.lower() in doc.lower():
    print(f" Found [doc_{i}]:{doc}")
  else:
    print(f"Missed[doc_{i}]:{doc}")

model=SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully")
print(f"Model produces vectors of size:{model.get_sentence_embedding_dimension()} dimensions")

sentence="ETL is used to clean and transform the data"
embedding=model.encode(sentence)
print(f"Input sentence:'{sentence}'")

print(f"Embedding type: {type(embedding)}")

print(f"Embedding shape:{embedding.shape}")

print(f"First 10 numbers:{embedding[:10].round(4)}")

print(f"Min value:{embedding.min():.4f}")

print(f"Max vslue: {embedding.max():.4f}")

documents=[


]
embedding=model.encode(documents)
query_keyboard="vehicle"

print(f"beyond search for:'{query_keyboard}'")

for i, doc in enumerate(documents):
  if query_keyboard.lower() in doc.lower():
    print(f" Found [doc_{i}]:{doc}")
  else:
    print(f"Missed[doc_{i}]:{doc}")
embedding=model.encode(documents)

from sklearn.metrics.pairwise import cosine_similarity

your_sentences = [
    "Switzerland is one of the best countries to explore",
    "I love eating healthy foods",
    "AI algorithms learn pattern from data"
]

your_embeddings = model.encode(your_sentences)

sim_your_01 = cosine_similarity(
    [your_embeddings[0]],
    [your_embeddings[1]]
)

sim_your_02 = cosine_similarity(
    [your_embeddings[0]],
    [your_embeddings[2]]
)

print('YOUR EXPERIMENT RESULTS')
print(f"Sentence A: '{your_sentences[0]}'")
print(f"Sentence B: '{your_sentences[1]}'")
print(f"Sentence C: '{your_sentences[2]}'")
print()

print(f"Similarity(A vs B): {sim_your_01[0][0]:.4f}")
print(f"Similarity(A vs C): {sim_your_02[0][0]:.4f}")

sample_docs = [
    "ETL means Extract, Transform and Load",
    "SQL is used to query databases",
    "Machine Learning trains models on data",
    "Python Pandas library is used for data manipulation and cleaning",
    "Neural networks are inspired by how the human brain works"
]

sample_ids = ["doc_1", "doc_2", "doc_3", "doc_4", "doc_5"]
sample_metadata = [
    {"subject": "Data Engineering", "topic":"ETL"},
    {"subject": "Data Engineering", "topic":"SQL"},
    {"subject": "Machine Learning", "topic":"ML Basics"},
    {"subject": "Python", "topic":"Pandas"},
    {"subject": "Machine Learning", "topic":"Neural Networks"}

]

collection.add(
    documents=sample_docs,
    ids=sample_ids,
    metadatas=sample_metadata
)

print("Documents in collection:")
print(collection.count())